
import React, { useState, useEffect } from 'react';
import { generateQuiz } from '../services/gemini';
import { QuizQuestion, Language, Subject } from '../types';

interface QuizProps {
  lang: Language;
  subject: Subject;
}

const UI_STRINGS = {
  en: {
    title: "Intelligence Check",
    desc: "Adaptive HOTS assessment generated by AI based on your mastery level.",
    loading: "Synthesizing level-specific questions...",
    finished: "Assessment Complete",
    resultText: "Accuracy Rate",
    tryOther: "Change Subject",
    scoreLabel: "Points",
    questionLabel: "QUEST",
    fromLabel: "OF",
    explanationLabel: "Academic Synthesis:",
    nextBtn: "Next Question",
    finishBtn: "Generate Result",
    questionsCount: "5 Questions",
    startBtn: "Launch Quiz",
    levelUp: "LEVEL UP: Mastery Level Increased.",
    levelDown: "DIFFICULTY ADJUSTED: Let's reinforce foundations.",
    masteryLabel: "CURRENT MASTERY",
    levels: ["NOVICE", "INTERMEDIATE", "EXPERT"],
    multiSelectHint: "Complex Choice: Select all applicable options.",
    submitAnswer: "Submit Analysis",
    topics: ['Functionalism', 'Conflict Theory', 'Digital Sociology', 'Social Dynamics', 'Identity & Culture']
  },
  id: {
    title: "Uji Kecerdasan",
    desc: "Penilaian HOTS adaptif yang disusun oleh AI berdasarkan tingkat penguasaan Anda.",
    loading: "Menyusun pertanyaan spesifik level...",
    finished: "Penilaian Selesai",
    resultText: "Tingkat Akurasi",
    tryOther: "Ganti Subjek",
    scoreLabel: "Skor",
    questionLabel: "SOAL",
    fromLabel: "DARI",
    explanationLabel: "Sintesis Akademik:",
    nextBtn: "Lanjut",
    finishBtn: "Lihat Hasil",
    questionsCount: "5 Soal",
    startBtn: "Mulai Kuis",
    levelUp: "LEVEL UP: Tingkat penguasaan meningkat.",
    levelDown: "KESULITAN DISESUAIKAN: Mari perkuat fondasi.",
    masteryLabel: "TINGKAT PENGUASAAN",
    levels: ["PEMULA", "MENENGAH", "AHLI"],
    multiSelectHint: "Pilihan Kompleks: Pilih semua jawaban yang relevan.",
    submitAnswer: "Kirim Analisis",
    topics: ['Fungsionalisme', 'Teori Konflik', 'Sosiologi Digital', 'Dinamika Sosial', 'Identitas & Budaya']
  },
  ar: {
    title: "اختبار الذكاء",
    desc: "تقييم تكيفي يعتمد على مستوى إتقانك.",
    loading: "جاري تجميع الأسئلة...",
    finished: "اكتمل التقييم",
    resultText: "معدل الدقة",
    tryOther: "تغيير الموضوع",
    scoreLabel: "النقاط",
    questionLabel: "سؤال",
    fromLabel: "من",
    explanationLabel: "التوليف الأكاديمي:",
    nextBtn: "التالي",
    finishBtn: "عرض النتيجة",
    questionsCount: "5 أسئلة",
    startBtn: "ابدأ الاختبار",
    levelUp: "ارتفع المستوى!",
    levelDown: "تم تعديل الصعوبة.",
    masteryLabel: "المستوى الحالي",
    levels: ["مبتدئ", "متوسط", "خبير"],
    multiSelectHint: "خيار معقد: اختر جميع الإجابات الصحيحة.",
    submitAnswer: "إرسال التحليل",
    topics: ['الوظيفية', 'نظرية الصراع', 'علم الاجتماع الرقمي', 'الديناميكيات الاجتماعية', 'الهوية والثقافة']
  }
};

const Quiz: React.FC<QuizProps> = ({ lang, subject }) => {
  const [questions, setQuestions] = useState<QuizQuestion[]>([]);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [loading, setLoading] = useState(false);
  const [score, setScore] = useState(0);
  const [showResult, setShowResult] = useState(false);
  const [selectedOptions, setSelectedOptions] = useState<number[]>([]);
  const [hasAnswered, setHasAnswered] = useState(false);
  const [activeTopic, setActiveTopic] = useState<string | null>(null);
  const [masteryLevels, setMasteryLevels] = useState<Record<string, number>>({});
  const [levelChangeMsg, setLevelChangeMsg] = useState<string | null>(null);

  const t = UI_STRINGS[lang];
  const isRtl = lang === 'ar';

  useEffect(() => {
    const savedLevels = localStorage.getItem('sociomind_mastery_levels');
    if (savedLevels) setMasteryLevels(JSON.parse(savedLevels));
  }, []);

  const saveLevel = (topic: string, newLevel: number) => {
    const updated = { ...masteryLevels, [topic]: newLevel };
    setMasteryLevels(updated);
    localStorage.setItem('sociomind_mastery_levels', JSON.stringify(updated));
  };

  const startQuiz = async (topic: string) => {
    setLoading(true);
    setQuestions([]);
    setCurrentIdx(0);
    setScore(0);
    setShowResult(false);
    setActiveTopic(topic);
    setLevelChangeMsg(null);
    const currentLevel = masteryLevels[topic] || 1;
    try {
      // Fix: Corrected generateQuiz call with missing subject argument
      const q = await generateQuiz(topic, lang, subject, currentLevel);
      setQuestions(q);
    } catch (e) { console.error(e); }
    finally { setLoading(false); }
  };

  const toggleOption = (idx: number) => {
    if (hasAnswered) return;
    const isMulti = questions[currentIdx].isMultiSelect;
    if (isMulti) {
      setSelectedOptions(prev => 
        prev.includes(idx) ? prev.filter(i => i !== idx) : [...prev, idx]
      );
    } else {
      setSelectedOptions([idx]);
      setHasAnswered(true);
      if (idx === questions[currentIdx].correctAnswers[0]) {
        setScore(s => s + 1);
      }
    }
  };

  const handleSubmitMulti = () => {
    if (hasAnswered) return;
    setHasAnswered(true);
    const correctOnes = [...questions[currentIdx].correctAnswers].sort();
    const selectedOnes = [...selectedOptions].sort();
    const isCorrect = correctOnes.length === selectedOnes.length && 
                      correctOnes.every((val, index) => val === selectedOnes[index]);
    if (isCorrect) setScore(s => s + 1);
  };

  const finishQuiz = () => {
    if (!activeTopic) return;
    const currentLevel = masteryLevels[activeTopic] || 1;
    let nextLevel = currentLevel;
    if (score >= 4 && currentLevel < 3) {
      nextLevel = currentLevel + 1;
      setLevelChangeMsg(t.levelUp);
    } else if (score <= 1 && currentLevel > 1) {
      nextLevel = currentLevel - 1;
      setLevelChangeMsg(t.levelDown);
    }
    if (nextLevel !== currentLevel) saveLevel(activeTopic, nextLevel);
    setShowResult(true);
  };

  const nextQuestion = () => {
    if (currentIdx < questions.length - 1) {
      setCurrentIdx(currentIdx + 1);
      setSelectedOptions([]);
      setHasAnswered(false);
    } else { finishQuiz(); }
  };

  if (loading) return (
    <div className="flex flex-col items-center justify-center py-40 gap-8">
      <div className="relative">
        <div className="w-20 h-20 border-4 border-indigo-100 rounded-full"></div>
        <div className="w-20 h-20 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin absolute top-0"></div>
      </div>
      <p className="text-slate-400 font-black text-xs uppercase tracking-[0.2em]">{t.loading}</p>
    </div>
  );

  if (showResult) return (
    <div className="max-w-2xl mx-auto space-y-8 animate-in zoom-in duration-500">
      <div className="bg-white p-12 rounded-[3.5rem] border border-slate-200 shadow-2xl text-center relative overflow-hidden">
        <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/5 rounded-full -mr-16 -mt-16 blur-2xl"></div>
        <div className="text-7xl mb-8">🏆</div>
        <h2 className="text-4xl font-black text-slate-900 tracking-tighter mb-4">{t.finished}</h2>
        
        <div className="bg-slate-50 p-10 rounded-[2rem] border border-slate-100 my-10">
          <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">{t.resultText}</p>
          <div className="text-8xl font-black text-indigo-600">{Math.round((score / questions.length) * 100)}%</div>
          <p className="text-slate-500 font-bold mt-4">{score} / {questions.length} Correct Analysis</p>
        </div>

        {levelChangeMsg && <div className="mb-8 p-5 bg-indigo-900 text-white rounded-2xl font-black text-[10px] uppercase tracking-widest">{levelChangeMsg}</div>}
        
        <div className="flex flex-col gap-4">
          <div className="flex justify-between items-center bg-slate-100/50 p-6 rounded-2xl border border-slate-100">
             <div className="text-left">
                <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{t.masteryLabel}</p>
                <p className="text-indigo-600 font-black text-lg">{t.levels[(masteryLevels[activeTopic || ''] || 1) - 1]}</p>
             </div>
             <div className="text-2xl">🎓</div>
          </div>
          <button onClick={() => { setQuestions([]); setActiveTopic(null); }} className="w-full bg-slate-900 text-white py-6 rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-black transition-all shadow-xl">{t.tryOther}</button>
        </div>
      </div>
    </div>
  );

  if (questions.length > 0) {
    const q = questions[currentIdx];
    return (
      <div className={`max-w-4xl mx-auto space-y-8 animate-in fade-in duration-300 ${isRtl ? 'text-right' : 'text-left'}`}>
        <div className="flex justify-between items-center">
          <div className="space-y-1">
             <p className="text-[10px] font-black uppercase tracking-widest text-slate-400">{t.questionLabel} {currentIdx + 1} {t.fromLabel} {questions.length}</p>
             <h4 className="text-indigo-600 font-black text-sm uppercase tracking-widest">{activeTopic}</h4>
          </div>
          <div className="flex gap-2">
            <span className="bg-indigo-600 text-white px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest">{t.scoreLabel}: {score}</span>
            <span className="bg-slate-900 text-white px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest">Lv. {masteryLevels[activeTopic || ''] || 1}</span>
          </div>
        </div>
        
        <div className="bg-white p-12 rounded-[3.5rem] border border-slate-200 shadow-2xl space-y-10">
          <div className="space-y-4">
            {q.isMultiSelect && <span className="inline-block bg-amber-100 text-amber-700 px-4 py-1 rounded-full text-[9px] font-black uppercase tracking-widest">{t.multiSelectHint}</span>}
            <h3 className="text-3xl font-black text-slate-900 leading-tight tracking-tighter">{q.question}</h3>
          </div>
          
          <div className="grid grid-cols-1 gap-4">
            {q.options.map((opt, i) => {
              const isSelected = selectedOptions.includes(i);
              const isCorrect = q.correctAnswers.includes(i);
              return (
                <button
                  key={i}
                  disabled={hasAnswered}
                  onClick={() => toggleOption(i)}
                  className={`group relative w-full text-left p-6 rounded-3xl border-2 transition-all flex items-center justify-between ${
                    hasAnswered
                      ? isCorrect
                        ? 'bg-emerald-50 border-emerald-500 text-emerald-900'
                        : isSelected
                          ? 'bg-rose-50 border-rose-500 text-rose-900'
                          : 'bg-white border-slate-100 opacity-40'
                      : isSelected 
                        ? 'bg-indigo-50 border-indigo-600 shadow-lg shadow-indigo-100'
                        : 'bg-white border-slate-200 hover:border-indigo-400 hover:bg-indigo-50/50'
                  }`}
                >
                  <div className="flex items-center gap-6">
                     <div className={`w-10 h-10 rounded-xl flex items-center justify-center font-black text-sm ${isSelected ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-400 group-hover:bg-indigo-100 group-hover:text-indigo-600'}`}>
                       {String.fromCharCode(65 + i)}
                     </div>
                     <span className="font-bold text-slate-700 text-lg">{opt}</span>
                  </div>
                  {hasAnswered && isCorrect && <span className="bg-emerald-500 text-white w-8 h-8 rounded-full flex items-center justify-center">✓</span>}
                  {hasAnswered && isSelected && !isCorrect && <span className="bg-rose-500 text-white w-8 h-8 rounded-full flex items-center justify-center">✕</span>}
                </button>
              );
            })}
          </div>

          {!hasAnswered && q.isMultiSelect && selectedOptions.length > 0 && (
             <button onClick={handleSubmitMulti} className="w-full bg-indigo-600 text-white py-6 rounded-2xl font-black uppercase tracking-widest text-xs shadow-xl hover:bg-indigo-700 transition-all active:scale-95">
                {t.submitAnswer}
             </button>
          )}

          {hasAnswered && (
            <div className="bg-slate-900 text-white p-10 rounded-[2.5rem] border border-white/5 animate-in slide-in-from-top-4 duration-500 space-y-6">
              <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-indigo-400">{t.explanationLabel}</h4>
              <p className="text-slate-300 text-lg leading-relaxed italic font-medium">"{q.explanation}"</p>
              <button onClick={nextQuestion} className="w-full bg-indigo-600 text-white py-5 rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-indigo-500 transition-all flex items-center justify-center gap-3">
                {currentIdx < questions.length - 1 ? t.nextBtn : t.finishBtn} ➔
              </button>
            </div>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className={`space-y-12 animate-in fade-in duration-500 ${isRtl ? 'text-right' : 'text-left'}`}>
      <header className="space-y-4 max-w-2xl">
        <div className="flex items-center gap-3 text-emerald-600 font-black text-xs uppercase tracking-widest">
           <span className="w-12 h-[2px] bg-emerald-600"></span>
           Assessment Center
        </div>
        <h2 className="text-5xl font-black text-slate-900 tracking-tighter">{t.title}</h2>
        <p className="text-slate-500 text-xl font-medium">{t.desc}</p>
      </header>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
        {t.topics.map((t_name) => (
          <button key={t_name} onClick={() => startQuiz(t_name)} className="group bg-white p-10 rounded-[3rem] border border-slate-200 shadow-sm hover:shadow-2xl transition-all text-center flex flex-col items-center relative overflow-hidden">
            <div className="absolute top-0 right-0 w-24 h-24 bg-emerald-500/5 rounded-full -mr-12 -mt-12 blur-xl"></div>
            <div className="w-24 h-24 bg-slate-50 rounded-[2rem] flex items-center justify-center text-5xl mb-8 group-hover:bg-emerald-600 group-hover:text-white transition-all transform group-hover:rotate-12">📝</div>
            <div className="space-y-2 mb-8">
              <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">{t.masteryLabel}</span>
              <h3 className="font-black text-slate-900 text-2xl tracking-tighter">{t_name}</h3>
              <p className="text-emerald-600 font-black text-xs">{t.levels[(masteryLevels[t_name] || 1) - 1]}</p>
            </div>
            <div className="w-full py-4 bg-emerald-50 rounded-2xl font-black text-[10px] uppercase tracking-widest text-emerald-600 group-hover:bg-emerald-600 group-hover:text-white transition-all">
              {t.startBtn} ➔
            </div>
          </button>
        ))}
      </div>
    </div>
  );
};

export default Quiz;
